"""add ondelete=cascade

Revision ID: a7a01c31bf77
Revises: cad8e891d761
Create Date: 2024-07-30 16:48:08.187679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a01c31bf77'
down_revision: Union[str, None] = 'cad8e891d761'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gigs_category_gigs_id_fkey', 'gigs_category', type_='foreignkey')
    op.create_foreign_key(None, 'gigs_category', 'gigs', ['gigs_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('gigs_file_gigs_id_fkey', 'gigs_file', type_='foreignkey')
    op.create_foreign_key(None, 'gigs_file', 'gigs', ['gigs_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('gigs_skill_gigs_id_fkey', 'gigs_skill', type_='foreignkey')
    op.create_foreign_key(None, 'gigs_skill', 'gigs', ['gigs_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gigs_skill', type_='foreignkey')
    op.create_foreign_key('gigs_skill_gigs_id_fkey', 'gigs_skill', 'gigs', ['gigs_id'], ['id'])
    op.drop_constraint(None, 'gigs_file', type_='foreignkey')
    op.create_foreign_key('gigs_file_gigs_id_fkey', 'gigs_file', 'gigs', ['gigs_id'], ['id'])
    op.drop_constraint(None, 'gigs_category', type_='foreignkey')
    op.create_foreign_key('gigs_category_gigs_id_fkey', 'gigs_category', 'gigs', ['gigs_id'], ['id'])
    # ### end Alembic commands ###
